# file: ansible/roles/common/tasks/main.yml
---

- name: Update packages
  tags: [yum]
  yum:
    name: '*'
    state: latest

- name: Install common packages
  tags: [yum] # for SELINUX policycoreutils-python
  yum:
    pkg: "{{ common_packages }}"
    state: installed

- name: Update locate database
  command: updatedb
  ignore_errors: yes

- name: install java
  tags: [java]
  yum:
    name: ["{{ java_version }}", "{{ java_version }}-devel"]
    state: installed

- name: set JAVA_HOME
  tags: [java]
  template:
    src: profile.d_jdk_home.sh.j2
    dest: /etc/profile.d/jdk_home.sh
